[config]
schemaVersion = "0.0.1"

[package]
namespace = "helskog"
name = "AutoConnect"
versionNumber = "1.0.0"
description = "Reconnect automatically if the server is full"
websiteUrl = "https://github.com/helskog/AutoConnect"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.733.2"

[build]
icon = "./logo_256.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Release/net6.0/AutoConnect.dll"
target = "./AutoConnect.dll"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[publish]
communities = ["v-rising"]
repository = "https://thunderstore.io"
[publish.categories]
v-rising = ["Client", "Mods", "Oakveil Update"]